---
title: 'R Notebook'
output: html_notebook
---

// we installed selenium
// we used free ports

```{r}

library(rvest)

```

```{r}

load_page <- function(year, onPageOne) {
  
  base <- 'https://www.espn.com/mlb/playerratings/_/year/'
  url <- if (onPageOne) paste(base, year, sep = '') else paste(base, year, '/page/2', sep = '')
  
  connected <- FALSE
  page <- NULL
  
  while(!connected) {
    result <- tryCatch({
      con <- url(url, 'rb')
      page <- read_html(con)
      close(con)
      connected <- TRUE
    }, error = function(e) {
      cat('\n', year, onPageOne, '\n\n')
    })
  }
  
  return(page)
  
}

```

```{r}

get_table_from_page <- function(page) {
  
  tables <- page %>%
    html_nodes('table') %>%
    html_table()
  
  table <- tables[[3]]
  return(table)
  
}

```

```{r}

clean_table <- function(table) {
  
  df <- unserialize(serialize(table, NULL))
  df <- df[-c(1, 2, 3), ]
  df <- df[, 1:4]
  names(df) <- c('Rank', 'Player', 'Team', 'Position')
  return(df)
  
}

```

```{r}

load_page_and_clean_table <- function(year, onPageOne) {
  
  page <- load_page(year, onPageOne)
  table <- get_table_from_page(page)
  table <- clean_table(table)
  return(table)
  
}

```

```{r}

get_dataframe_for_year <- function(year) {
  
  df_1 <- load_page_and_clean_table(year, TRUE)
  df_2 <- load_page_and_clean_table(year, FALSE)
  combined_df <- rbind(df_1, df_2)
  return(combined_df)
  
}

```

```{r}

save_dataframe_to_csv <- function(df, year) {
  
  file_name = paste('top_100_each_year/top_players_', year, '.csv', sep = '')
  write.csv(df, file = file_name, row.names = FALSE)
  
}

```

```{r}

last_year <- as.numeric(format(Sys.Date(), '%Y')) - 1
num_years <- last_year - 2008 + 1
years <- seq(last_year, by = -1, length.out = num_years)

for (year in years) {
  df <- get_dataframe_for_year(year)
  save_dataframe_to_csv(df, year)
}

```